# Generated by Django 4.1.3 on 2022-11-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contacts', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('SHOES', 'SHOES'), ('FLASH', 'FLASH'), ('PHONE', 'PHONE'), ('CHARGER', 'CHARGER'), ('EXTENSION', 'EXTENSION'), ('EARPHONES', 'EARPHONES'), ('BLUETOOTH', 'BLUETOOTH'), ('SPEAKER', 'SPEAKER')], max_length=100)),
                ('order', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('local', 'local'), ('ugandan', 'ugandan'), ('foreign', 'foreign')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omarApp.order')),
            ],
        ),
    ]
